# Generated by Django 2.0 on 2021-08-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(default='product category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='productname', max_length=255)),
                ('pro_image', models.ImageField(default='xyz.jpg', upload_to='productimage/')),
                ('pro_price', models.FloatField(default=0.0)),
                ('pro_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='firstname', max_length=255)),
                ('lname', models.CharField(default='lasttname', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(default=123)),
                ('address', models.CharField(default='address', max_length=255)),
                ('passwd', models.CharField(default='password', max_length=255)),
                ('OTP', models.CharField(default='1234', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='firstname', max_length=255)),
                ('lname', models.CharField(default='lasttname', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(default=123)),
                ('address', models.CharField(default='address', max_length=255)),
                ('passwd', models.CharField(default='password', max_length=255)),
                ('OTP', models.CharField(default='1234', max_length=6)),
            ],
        ),
    ]
