# Generated by Django 2.0 on 2021-08-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='fname',
            new_name='Shop_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='lname',
            new_name='Sname',
        ),
    ]
